import type { GetServerSideProps } from "next";

import { Title } from "@mantine/core";

import Carousel from "@/components/product/product-carousel";

import { prisma } from "@/prisma/client";
import type { products } from "@prisma/client";

export const getServerSideProps: GetServerSideProps = async () => {
  // Try to read from the DB views generated by Supabase/Prisma.
  // If the view is missing or its columns changed (common during migrations),
  // gracefully fall back to the products table or to a local mock so the page
  // doesn't crash in production.
  let specials: any[] = [];
  let random_picks: any[] = [];

  try {
    specials = await prisma.get_specials.findMany();
    random_picks = await prisma.get_random_picks.findMany();
  } catch (err) {
    // eslint-disable-next-line no-console
    console.warn("get_specials/get_random_picks query failed, falling back:", err);

    try {
      // Fallback to products table (works if views aren't available)
      specials = await prisma.products.findMany({
        take: 8,
        orderBy: { created_at: "desc" },
      });

      random_picks = await prisma.products.findMany({
        take: 8,
        skip: 8,
      });
    } catch (err2) {
      // Last-resort fallback to local mock data
      // eslint-disable-next-line no-console
      console.warn("products fallback failed, using mock data:", err2);
      const productsModule = await import("../__mocks__/data/products.json");
      const products = productsModule.default ?? productsModule;

      specials = (products as any[]).slice(0, 8);
      random_picks = (products as any[]).slice(8, 16);
    }
  }

  return {
    props: {
      specials: JSON.parse(JSON.stringify(specials)),
      random_picks: JSON.parse(JSON.stringify(random_picks)),
    },
  };
};

export default function Home({
  specials,
  random_picks,
}: {
  specials: products[];
  random_picks: products[];
}) {
  return (
    <div className="space-y-10">
      <div className="flex flex-col space-y-3">
        <Title order={2} weight={800} className="text-center">
          Weekly Specials
        </Title>

        <Carousel products={specials} />
      </div>
      <div className="flex flex-col space-y-3">
        <Title order={2} weight={800} className="text-center">
          Top Picks
        </Title>

        <Carousel products={random_picks} />
      </div>
    </div>
  );
}
